baseURL = "http://example.org/"
languageCode = "en-us"
title = "Esper"
disableKinds = ["taxonomyTerm"]

[params]
    description = "Ads are bad!"
    font = "Arial"
    fontSize = "1rem"
    borderColor = "red"
    borderWidth = "0.25rem"
    backgroundColor = "white"